### ISSUE TITLE
cant download names.zip file 

### ISSUE THREAD

**Issue by ebin123456** [sholiday/genderPredictor#4]
hi i am getting following error
names.pickle does not exist, generating
names.zip does not exist, downloading from github
Traceback (most recent call last):
  File "USSSALoader.py", line 84, in <module>
    getNameList()
  File "USSSALoader.py", line 18, in getNameList
    downloadNames()
  File "USSSALoader.py", line 55, in downloadNames
    u = urllib2.urlopen('https://github.com/downloads/sholiday/genderPredictor/names.zip')
  File "C:\Python27\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 410, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 629, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Python27\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 10054] An existing connection was forcibly closed by the remote host>

**Comment by theopak** [comment]
Are you using OS X? I had the same issue and the solution was to update OpenSSL: https://github.com/kennethreitz/requests/issues/2022

**Comment by ebin123456** [comment]
i am using windows 7
